apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: monitoring
  - apiVersion: source.toolkit.fluxcd.io/v1
    kind: HelmRepository
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      interval: 10m
      url: https://grafana.github.io/helm-charts
  - apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    metadata:
      name: loki-stack
      namespace: monitoring
    spec:
      chart:
        spec:
          chart: loki-stack
          sourceRef:
            kind: HelmRepository
            name: grafana
          version: 2.x
      interval: 10m
      timeout: 2m
