apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: master-provisioner
  namespace: flux-system
spec:
  interval: 1m
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: getting-started-with-gitops
