---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: getting-started-with-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/developer-friendly/getting-started-with-gitops
